/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grunwald;

import javax.swing.DefaultListModel;

/**
 *
 * @author mateusz
 */
public class Grunwald extends javax.swing.JFrame {

    /**
     * Creates new form Grunwald
     */
    public Grunwald() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        poleRok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        guzikGrunwald = new javax.swing.JButton();
        guzikWypisz = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        poleDzien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboMiesiac = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        check30 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        radioDni = new javax.swing.JRadioButton();
        radioLata = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        guzikZmniejsz = new javax.swing.JButton();
        guzikFormularz = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        poleWydarzenie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guzikWszystkie = new javax.swing.JButton();
        guzikDodaj = new javax.swing.JButton();
        guzikKasuj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poleRok.setPreferredSize(new java.awt.Dimension(100, 27));
        jPanel1.add(poleRok);

        jLabel1.setText("Rok");
        jPanel1.add(jLabel1);

        guzikGrunwald.setText("Grunwald");
        guzikGrunwald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikGrunwaldActionPerformed(evt);
            }
        });
        jPanel1.add(guzikGrunwald);

        guzikWypisz.setText("Wypisz");
        guzikWypisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikWypiszActionPerformed(evt);
            }
        });
        jPanel1.add(guzikWypisz);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poleDzien.setPreferredSize(new java.awt.Dimension(100, 27));
        jPanel2.add(poleDzien);

        jLabel2.setText("Dzień");
        jPanel2.add(jLabel2);

        comboMiesiac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(comboMiesiac);

        jLabel7.setText("Miesiąc");
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        check30.setText("30");
        jPanel3.add(check30);

        getContentPane().add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        radioGroup.add(radioDni);
        radioDni.setSelected(true);
        radioDni.setText("dni");
        jPanel4.add(radioDni);

        radioGroup.add(radioLata);
        radioLata.setText("lata");
        jPanel4.add(radioLata);

        getContentPane().add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        guzikZmniejsz.setText("Zmniejsz");
        guzikZmniejsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikZmniejszActionPerformed(evt);
            }
        });
        jPanel5.add(guzikZmniejsz);

        guzikFormularz.setText("Formularz");
        guzikFormularz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikFormularzActionPerformed(evt);
            }
        });
        jPanel5.add(guzikFormularz);

        getContentPane().add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poleWydarzenie.setPreferredSize(new java.awt.Dimension(100, 27));

        jLabel6.setText("Wydarzenie");

        guzikWszystkie.setText("Wszystkie");
        guzikWszystkie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikWszystkieActionPerformed(evt);
            }
        });

        guzikDodaj.setText("Dodaj");
        guzikDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikDodajActionPerformed(evt);
            }
        });

        guzikKasuj.setText("Kasuj");
        guzikKasuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikKasujActionPerformed(evt);
            }
        });

        modelListy = new DefaultListModel<>();
        lista.setModel(modelListy);
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guzikDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guzikWszystkie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guzikKasuj))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(poleWydarzenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poleWydarzenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guzikDodaj)
                    .addComponent(guzikWszystkie)
                    .addComponent(guzikKasuj))
                .addContainerGap())
        );

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guzikGrunwaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikGrunwaldActionPerformed
        poleRok.setText("1410");
    }//GEN-LAST:event_guzikGrunwaldActionPerformed

    private void guzikWypiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikWypiszActionPerformed
        System.out.println(poleRok.getText());
    }//GEN-LAST:event_guzikWypiszActionPerformed

    private String wyciagnijDate(){
        String data = "";
        String rok = poleRok.getText();
        String miesiac = comboMiesiac.getSelectedItem().toString();
//        Integer miesiacLiczba = Integer.parseInt(miesiac);
//        String miesiacStr  = "";
//        if(miesiacLiczba < 10)  miesiacStr = "0" + miesiac.toString();
        Integer dzienLiczba = Integer.parseInt(poleDzien.getText());
        String dzienStr = poleDzien.getText();
        if(dzienLiczba < 10) dzienStr = "0" + dzienLiczba.toString();
        
        data += poleRok.getText() + "-";
        data += miesiac + "-";
        data += dzienStr;
               
        return data;
    }
    
    private void guzikFormularzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikFormularzActionPerformed
        String wypiszDate = wyciagnijDate();
        System.out.println(wypiszDate);
    }//GEN-LAST:event_guzikFormularzActionPerformed

    private void guzikWszystkieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikWszystkieActionPerformed
        for(int i=0; i<modelListy.size(); i++)
            System.out.println(modelListy.getElementAt(i));
    }//GEN-LAST:event_guzikWszystkieActionPerformed

    private void guzikDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikDodajActionPerformed
        String data = wyciagnijDate();
        String doTabeli = poleWydarzenie.getText() + " " + data;
        modelListy.addElement(doTabeli);
    }//GEN-LAST:event_guzikDodajActionPerformed

    private void guzikZmniejszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikZmniejszActionPerformed
        Integer dzien = Integer.parseInt(poleDzien.getText());
        Integer rok = Integer.parseInt(poleRok.getText());
        int miesiac = comboMiesiac.getSelectedIndex();
        
        if(radioDni.isSelected()){
            if(check30.isSelected())
                if(dzien == 1)
                    poleDzien.setText("30");
                else {dzien -= 1;
                    poleDzien.setText(dzien.toString());
                }
            else{
                    if(dzien == 1)
                        poleDzien.setText("31");
                        
                    else {dzien -= 1;
                        poleDzien.setText(dzien.toString());
                    }
                } 
        }
        
        if(radioLata.isSelected())
            rok -= 1;

        poleRok.setText(rok.toString());
    }//GEN-LAST:event_guzikZmniejszActionPerformed

    private void guzikKasujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikKasujActionPerformed
//        modelListy.removeAllElements();
          int j = lista.getSelectedIndex();
          modelListy.removeElementAt(j);
    }//GEN-LAST:event_guzikKasujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grunwald.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grunwald.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grunwald.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grunwald.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grunwald().setVisible(true);
            }
        });
    }
    private DefaultListModel <String> modelListy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check30;
    private javax.swing.JComboBox<String> comboMiesiac;
    private javax.swing.JButton guzikDodaj;
    private javax.swing.JButton guzikFormularz;
    private javax.swing.JButton guzikGrunwald;
    private javax.swing.JButton guzikKasuj;
    private javax.swing.JButton guzikWszystkie;
    private javax.swing.JButton guzikWypisz;
    private javax.swing.JButton guzikZmniejsz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField poleDzien;
    private javax.swing.JTextField poleRok;
    private javax.swing.JTextField poleWydarzenie;
    private javax.swing.JRadioButton radioDni;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radioLata;
    // End of variables declaration//GEN-END:variables
}
